[package]
edition = "2018"
name = "hck"
version = "0.1.1-beta.2"
authors = ["Seth Stadick <sstadick@gmail.com>"]
license = "MIT"
repository = "https://github.com/sstadick/hck"
description = "A sharp cut(1) clone."
documentation = "https://docs.rs/hck"
readme = "README.md"
categories = ["text-processing", "command-line-interface"]
keywords = ["text", "cli"]

[profile.release]
lto = true
codegen-units = 1

[dependencies]
regex = "1.5.4"
structopt = "0.3.21"
thiserror = "1.0.25"

[dev-dependencies]
tempfile = "3.2.0"
